FROM jetbrains/teamcity-server
ADD https://jdbc.postgresql.org/download/postgresql-42.1.4.jar /data/teamcity_server/datadir/lib/jdbc/postgresql-42.1.4.jar
ADD https://teamcity.jetbrains.com/guestAuth/repository/download/TeamCityPluginsByJetBrains_TeamcityCommitHooks_Build/.lastPinned/teamcity-commit-hooks.zip /data/teamcity_server/datadir/plugins/teamcity-commit-hooks.zip
